---
- name: Retrieve BGP neighbor information
  hosts: localhost
  tasks:
  - command: cat routes
    register: juniper_output
  - name: T1
    debug: msg={{juniper_output.stdout}}
  - debug: msg={{ juniper_output.stdout | parse_cli_textfsm('textfsm/routes_template') }}