---
- name: Extract NA hosts
  hosts: localhost
  vars:
     csvfile: "{{lookup('file', 'search_result.csv')}}"
  tasks:
    - template:
           src: "templates/iterate.j2"
           dest: "vars/iterate.yml"
    - include_vars: 
           dir: vars
           files_matching: iterate.yml
    - template:
           src: "templates/compare.j2"
           dest: "vars/compare.yml"
    - include_vars: 
           dir: vars
           files_matching: compare.yml
    - template:
           src: "templates/before.j2"
           dest: "vars/before.yml"
    - template:
           src: "templates/after.j2"
           dest: "vars/after.yml"
    - include_vars: 
           dir: vars
    - set_fact: compare={{before|difference(after)}}
    - debug: var=compare