---
- name: Run pre-tests
  hosts: nxos
  connection: network_cli
  tasks:
    - nxos_command:
        commands:
         - show vrf
      register: vrf
    - set_fact: vrfname={{ vrf.stdout[0] | parse_cli('cli_filters/vrf.yml') }}
    - debug: var=vrfname
    - template: 
         src: test.j2
         dest: "commands.yml"
- name: run commands
  hosts: nxos
  connection: network_cli
  vars_files: commands.yml
  tasks:
    - nxos_command: commands="{{item}}"
      register: results
      loop: "{{showcommands}}"
    - debug: var=results
  