---
- name: Collect ip objects
  hosts: nxos
  vars_files: "vars1.yml"
#Problem Azure uses /32 subnet while object gives output "host" instead of /32
  tasks:
      - nxos_command:
           commands:
              - show object-group O365src | json
              - show object-group O365dst | json
        register: results
      - debug: var=results
#Use this task with parse_cli to extract list of of prefixes with sequence numbers
#After collecting the information we need to add /32 after all host avi_networks
#I can only do this in three steps, use ipaddr ('net') filter to collect CIDR blocks and use ('host')filter for /32 networks
      - nxos_command:
           commands:
              - show object-group O365src
              - show object-group O365dst
        register: iosresults        
      - set_fact: ioso365src={{ iosresults.stdout[0] | parse_cli('cli_filter/0365.yml') }}
      - set_fact: ioso365dst={{ iosresults.stdout[1] | parse_cli('cli_filter/0365.yml') }}
      - debug: var=ioso365src
      - debug: var=ioso365dst
#Trying to join to lists together
      -  set_fact: realprefixes="{{ioso365dst.subnets|map(attribute="net_ip")|ipaddr('net')}}"
      -  set_fact: hostprefixes="{{ioso365dst.subnets|map(attribute="net_ip")|ipaddr('host')}}"
#o365livelist is the list containing only the subnets in a same format as we receive from Microsoft
      -  set_fact: o365livelist="{{realprefixes+hostprefixes}}"
#      - set_fact: o365livelist="{{ ioso365dst.subnets|map(attribute="net_ip")|}}" | blocking this entry to test IP addr filter
      - debug: var=o365object
#user the variable from vars_files and extract the subnets
      - set_fact: o365list="{{ o365object|map(attribute="net_ip")|list }}"
      - set_fact: 
            remove: "{{ o365list | difference(o365prfx) }}"
            add: "{{ o365prfx | difference(o365list) }}"
      - debug: var=o365prfx
      - debug: var=o365list
      - debug: var=o365livelist
      - debug: var=add
      - debug: var=remove
      - debug: msg={{ o365object | selectattr("net_ip", "equalto", "remove") | map(attribute="seqno") | list }}

